config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  namespace :api do
    namespace :v1 do
      namespace :mockup do
        namespace :seat_trackings do
          get 'boardingpass/index'
          post 'pax/list'
          post 'trips/all'
        end
      end
    end
  end

  post 'passenger/reload_list'
  post 'passenger/assign_seat'
  get 'passenger/get_terminal_pax_list'
  get 'passenger/update_passenger_list'
  get 'passenger/history'
  get 'passenger/search'

  namespace :api do
    namespace :v1 do
      get 'trip/index'
      post 'trip/confirm'
      post 'trip/clean_with_reload'
      post 'trip/end_trip'
      post 'passenger/info', to: 'passenger#show'
    end
  end

  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper
  include HomeHelper

  helper_method :deck_color

  def index
    @internet = true
    
    begin
      loading_today_data
    rescue Faraday::ConnectionFailed
      @internet = false
    end

    @facade = ::PaxListFacade.new
  end

  private

  def loading_today_data
    return if TripValidation.today_is_loaded?

    Sidekiq.redis(&:flushdb) # be careful with this command, should run before any sidekiq enqueue.
    Trips::Reset.call
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def deck_color(passenger)
    if vessels?
      case passenger.deck
        when 'first_deck'
          'bg-orange'
        when 'second_deck'
          'bg-dark'
        when 'third_deck'
          'bg-green'
      end
    else
      passenger.main? ? 'bg-orange' : 'bg-dark'
    end
  end
end

app/views/home/_decks.haml
#decks.tab-pane.fade.show.active{"aria-labelledby" => "home-tab", :role => "tabpanel"}
  .deck.row
    .col-md-6
      = render partial: 'home/main_deck'

    .col-md-6
      = render partial: 'home/lower_deck'

app/views/home/_history_list.haml
.p-4.js-history-table
  %table.table.table-hover
    %thead
      %tr
        %th{:scope => "col"} #
        %th{:scope => "col"} Name
        %th{:scope => "col"} Passport
        %th{:scope => "col"} No. of Trip
        %th{:scope => "col"} Synchronized
    %tbody
      - names = Passenger.name_map
      - @facade.pax_history.each_with_index do |passenger,i|
        -i+=1
        %tr
          %th{:scope => "row"}= i
          %td
            = link_to passenger_history_path(passport: passenger.passport), remote: true, class:'text-decoration-none' do
              = names[passenger.passport]
          %td= passenger.passport
          %td= passenger.counter
          %td
            -if @facade.count_sync[passenger.passport] == passenger.counter
              %i.fa.fa-check-circle.synchronized

#js-pax-history.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Modal title
      .modal-body{style: 'max-height: 80vh;overflow-y: auto'}
        \...

app/views/home/_logs.haml
.logs.d-flex.flex-column
  %button.btn.btn-green.btn-sm.js-update-pax-list.mb-2{title: 'Update current trip'}
    %i.fa.fa-edit
    %span Pax
  - if not @trip.nil? || @passengers.empty?
    %span.small.mb-2 Updated at #{@passengers.last.created_at.strftime('%d/%m/%Y %H:%M')}

  %button.btn.btn-dark.btn-sm.js-get-terminal-pax-list{title: 'Update current trip', disabled: @trip&.origin_is_singapore?}
    %i.fa.fa-edit
    %span Terminal Pax

app/views/home/_lower_deck.haml
#lower-deck
  %label.h1.mt-5 Lower Deck

  .shipbox
    -#.ship-head.row
    -#  #curved-corner-topleft
    -#  #curved-corner-topright
    .row.seat-row.mb-5{style: 'padding-left: 54px;'}
      .seat.empty
      .seat.seat-standard.active{class: "lower-l1 #{@seats['L1'] ? 'checked' : ''}", 'data-toggle':"tooltip",'data-placement':"top"} L1
      .seat.seat-standard.active{class: "lower-l2 #{@seats['L2'] ? 'checked' : ''}", 'data-toggle':"tooltip",'data-placement':"top"} L2
      .seat.seat-standard.active{class: "lower-l3 #{@seats['L3'] ? 'checked' : ''}", 'data-toggle':"tooltip",'data-placement':"top"} L3

      .seat.empty

      .seat.seat-standard.active{class: "lower-l4 #{@seats['L4'] ? 'checked' : ''}", 'data-toggle':"tooltip",'data-placement':"top"} L4
      .seat.seat-standard.active{class: "lower-l5 #{@seats['L5'] ? 'checked' : ''}", 'data-toggle':"tooltip",'data-placement':"top"} L5
      .seat.seat-standard.active{class: "lower-l6 #{@seats['L6'] ? 'checked' : ''}", 'data-toggle':"tooltip",'data-placement':"top"} L6
      .seat.empty
    -seat_no = 7
    -12.times do |i|
      .row.seat-row
        -if [0,1,2,7].include?(i)
          .seat.empty
        -else
          .seat.seat-standard.active{class: "lower-l#{seat_no} #{@seats["L#{seat_no}"] ? 'checked' : ''}", 'data-toggle':"tooltip",'data-placement':"top"}
            = "L#{seat_no}"
            -seat_no += 1
        -4.times do
          .seat.seat-standard.active{class: "lower-l#{seat_no} #{@seats["L#{seat_no}"] ? 'checked' : ''}", 'data-toggle':"tooltip",'data-placement':"top"}
            = "L#{seat_no}"
            -seat_no += 1

        .seat.empty

        -4.times do
          .seat.seat-standard.active{class: "lower-l#{seat_no} #{@seats["L#{seat_no}"] ? 'checked' : ''}", 'data-toggle':"tooltip",'data-placement':"top"}
            = "L#{seat_no}"
            -seat_no += 1
        -if [0,1,2,7].include?(i)
          .seat.empty
        -else
          .seat.seat-standard.active{class: "lower-l#{seat_no} #{@seats["L#{seat_no}"] ? 'checked' : ''}", 'data-toggle':"tooltip",'data-placement':"top"}
            = "L#{seat_no}"
            -seat_no += 1

app/views/home/_main_deck.haml
#main-deck
  %label.h1.mt-5{style: 'width: 90%;'} Main Deck

  .shipbox
    -#.ship-head.row
    -#  #curved-corner-topleft
    -#  #curved-corner-topright
    .row.seat-row
      .seat.empty
      .seat.empty
      .seat.seat-sw.active{class: "main-v2 #{@seats['V2'] ? 'checked' : ''}",'data-toggle':"tooltip",'data-placement':"top"} V2
      .seat.seat-sw.active{class: "main-v1 #{@seats['V1'] ? 'checked' : ''}",'data-toggle':"tooltip",'data-placement':"top"} V1

      .seat.empty

      .seat.seat-sw.active{class: "main-v6 #{@seats['V6'] ? 'checked' : ''}",'data-toggle':"tooltip",'data-placement':"top"} V6
      .seat.empty
      .seat.empty
      .seat.empty
    .row.seat-row
      .seat.empty
      .seat.seat-sw.active{class: "main-v3 #{@seats['V3'] ? 'checked' : ''}",'data-toggle':"tooltip",'data-placement':"top"} V3
      .seat.empty
      .seat.empty

      .seat.empty

      .seat.empty
      .seat.empty
      .seat.seat-sw.active{class: "main-v7 #{@seats['V7'] ? 'checked' : ''}", 'data-toggle':"tooltip",'data-placement':"top"} V7
      .seat.empty
    .row.seat-row.mb-5
      .seat.empty
      .seat.empty
      .seat.seat-sw.active{class: "main-v4 #{@seats['V4'] ? 'checked' : ''}",'data-toggle':"tooltip",'data-placement':"top"} V4
      .seat.seat-sw.active{class: "main-v5 #{@seats['V5'] ? 'checked' : ''}",'data-toggle':"tooltip",'data-placement':"top"} V5

      .seat.empty

      .seat.seat-sw.active{class: "main-v9 #{@seats['V9'] ? 'checked' : ''}",'data-toggle':"tooltip",'data-placement':"top"} V9
      .seat.seat-sw.active{class: "main-v8 #{@seats['V8'] ? 'checked' : ''}",'data-toggle':"tooltip",'data-placement':"top"} V8
      .seat.empty
      .seat.empty

    - seat_no = 1
    -7.times do
      .row.seat-row
        - 4.times do
          .seat.seat-standard.active{class:"main-m#{seat_no} #{@seats["M#{seat_no}"] ? 'checked' : ''}", 'data-toggle':"tooltip",'data-placement':"top"}
            = "M#{seat_no}"
            -seat_no += 1

        .seat.empty
        - 4.times do
          .seat.seat-standard.active{class:"main-m#{seat_no} #{@seats["M#{seat_no}"] ? 'checked' : ''}", 'data-toggle':"tooltip",'data-placement':"top"}
            = "M#{seat_no}"
            -seat_no += 1
    -seat_no1 = seat_no
    -seat_no2 = seat_no + 4
    - 4.times do
      .row.seat-row
        .seat.empty
        .seat.empty
        .seat.empty
        .seat.seat-standard.active{class:"main-m#{seat_no1} #{@seats["M#{seat_no}"] ? 'checked' : ''}",'data-toggle':"tooltip",'data-placement':"top"}
          = "M#{seat_no1}"
          -seat_no1 += 1
        .seat.empty
        .seat.seat-standard.active{class:"main-m#{seat_no2} #{@seats["M#{seat_no}"] ? 'checked' : ''}",'data-toggle':"tooltip",'data-placement':"top"}
          = "M#{seat_no2}"
          -seat_no2 += 1
        .seat.empty
        .seat.empty
        .seat.empty


    .row.back-ship

      .iconlist.mt-2
        .icon.checked{:title => "Confirmed"}
          Occupied
        .icon.zone-standard{:title => "Standard"}
          Vacant

app/views/home/_passenger_list.haml
.passenger-list
  .row.d-flex.justify-content-end.flex-row.js-search-group
    .input-group.mb-3.mt-2{style: 'max-width: 300px'}
      %input.form-control.js-search-pax{"aria-describedby" => "basic-addon2", "aria-label" => "Recipient's username",
      :placeholder => "Name", :type => "text",
      "data-action" => "keyup->passenger#search_passenger",
      "data-passenger-trip-id-param" => @facade.trip&.trip_id}/
      %span#basic-addon2.input-group-text
        %i.fa.fa-search{"data-action" => "click->passenger#btn_search_passenger", style: 'cursor: pointer'}
    .p-2{style: 'max-width: 100px;margin-left: -15px'}
      %button.btn.btn-green{"data-action" => "click->passenger#clear_search"}
        Clear
  .row
    %table.table.table-hover
      %thead
        %tr
          %th{:scope => "col"} #
          %th{:scope => "col"} Name
          %th{:scope => "col"} Deck
          %th{:scope => "col"} Seat
          %th{:scope => "col"} Passport
          %th{:scope => "col"} Phone
          %th{:scope => "col"} Boarding Pass
      %tbody
        - @facade.pax_in_order.each_with_index do |passenger,i|
          -i+=1
          %tr
            %th{:scope => "row"}= i
            %td
              %a.text-decoration-none{"data-action" => "passenger#manuallyAssignSeat", href: '#',
                    "data-passenger-id-param" => passenger.id,
                    "data-passenger-name-param" => passenger.name}= passenger.name
            = render :partial => 'home/td_deck', locals: {passenger:passenger}
            = render :partial => 'home/td_seat', locals: {passenger:passenger}
            %td= passenger.passport
            %td= passenger.phone
            %td= passenger.boarding_pass

app/views/home/_td_deck.haml
%td.js-td-deck{id: "js-td-deck-#{passenger.id}"}
  -if passenger.seat
    .deck-seat.badge{class: deck_color(passenger)}
      -if vessels?
        = passenger.deck&.titleize
      -else
        = passenger.main? ? 'main' : 'lower'

app/views/home/_td_seat.haml
%td.js-td-seat{id: "js-td-seat-#{passenger.id}"}
  %span.seat.badge= passenger.seat

app/views/home/_trip_name.haml
%h5.trip-number.mb-3
  = @facade.trip ? "Trip #{@facade.trip.trip_id}" : "NO TRIP"
  %small
    %span.confirmed-count= "#{@facade.confirmed_count}"
    = "/ #{@facade.pax_in_order.size})"
  - if not @facade.trip.nil? || @facade.pax_in_order.empty?
    %small.mb-2{style: 'color: lightgray; font-weight: 100;font-size: 12px'} Updated at #{@facade.pax_in_order.last.created_at.strftime('%d/%m/%Y %H:%M')}

app/views/home/index.html.haml
.container-fluid
  .row
    .col-sm.min-vh-100.no-padding
      %nav.navbar.navbar-light.bg-light.text-center.d-flex
        %a.row.logo.navbar-brand{:href => "/"}
          %h1 SEAT TRACKING DEMO
        .actions.d-flex.justify-content-start

      .col-md-12.d-flex.justify-content-between
        .d-flex.justify-content-lg-start{style: 'margin: 15px 0px 0px 15px;'}
          %button.btn.btn-dark.btn-sm.js-update-pax-list{title: 'Update current trip', style: 'margin: 0px 5px'}
            %i.fa.fa-cloud-download-alt
            %span Update Pax

          = link_to '#', class: 'btn btn-danger btn-sm js-end-trip', style: 'color:white !important' do
            %i.fa.fa-flag
            %span End Trip
      .main-content{"data-controller" => "passenger"}
        .row.ferries
          .decks.col-md-12.d-flex.flex-column
            .d-flex.align-items-start
              #v-pills-tab.nav.flex-column.nav-pills.me-3{"aria-orientation" => "vertical",
              :role => "tablist", style: 'background: darkgray;'}
                %button#v-pills-home-tab.nav-link{"aria-controls" => "v-pills-home", "aria-selected" => "true", "data-bs-target" => "#v-pills-home", "data-bs-toggle" => "pill", :role => "tab", :type => "button",
                class: params[:history] ? '' : 'active'}
                  %i.fa.fa-ship
                %button#v-pills-profile-tab.nav-link{"aria-controls" => "v-pills-profile", "aria-selected" => "false", "data-bs-target" => "#v-pills-profile", "data-bs-toggle" => "pill", :role => "tab", :type => "button",
                class: params[:history] ? 'active' : ''}
                  %i.fa.fa-history

              #v-pills-tabContent.tab-content.pill-content
                #v-pills-home.tab-pane.fade.show{"aria-labelledby" => "v-pills-home-tab", :role => "tabpanel",
                class: params[:adv] ? '' : 'active'}
                  .container
                    = render :partial => 'home/trip_name'

                    %ul#myTab.nav.nav-tabs{:role => "tablist"}
                      %li.nav-item{:role => "presentation"}
                        %button#home-tab.nav-link.active{"aria-controls" => "home", "aria-selected" => "true",
                        "data-bs-target" => "#decks", "data-bs-toggle" => "tab", :role => "tab", :type => "button"} Deck
                      %li.nav-item{:role => "presentation"}
                        %button#profile-tab.nav-link{"aria-controls" => "profile", "aria-selected" => "false",
                        "data-bs-target" => "#passenger-list", "data-bs-toggle" => "tab", :role => "tab", :type => "button"} Passenger


                    .tab-content
                      = render partial: 'home/vessels/index'
                      #passenger-list.passenger.tab-pane.fade{"aria-labelledby" => "home-tab", :role => "tabpanel"}
                        = render :partial => 'home/passenger_list'


                #v-pills-profile.tab-pane{"aria-labelledby" => "v-pills-profile-tab", :role => "tabpanel",
                class: params[:history] ? 'active' : ''}
                  .row.d-flex.justify-content-end.js-search-group
                    .input-group.mb-3.mt-2{style: 'max-width: 300px'}
                      %input.form-control.js-search-pax{"aria-describedby" => "basic-addon2", "aria-label" => "Recipient's username",
                      :placeholder => "Name", :type => "text",
                      "data-action" => "keyup->passenger#search_passenger",
                      "data-passenger-trip-id-param" => ''}/
                      %span#basic-addon2.input-group-text
                        %i.fa.fa-search{"data-action" => "click->passenger#btn_search_passenger", style: 'cursor: pointer;'}
                    .p-2{style: 'max-width: 100px;margin-left: -10px;'}
                      %button.btn.btn-green{"data-action" => "click->passenger#clear_search"}
                        Clear
                  = render :partial => 'home/history_list'


.js-modal-assign-seat.modal{:role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5.modal-title Assign Seat
      .modal-body
        = hidden_field_tag :seat_option, Seat.labels, class: 'js-seat-label'
        = text_field_tag :seat, nil, class: 'js-input-seat form-control', id: 'js-input-seat', autocomplete:"off"
      .modal-footer
        %button.btn.btn-primary.js-submit{:type => "button"} Submit